### ISSUE TITLE
Endpoint to delete Invitations (feature request)

### ISSUE THREAD

**Issue by agranero** [fmarco/django-rest-invitations#4]
Hey there! I realized that there is no endpoint which enables to delete invitations, and I thought that it would be interesting to have it included in the package, for consistency with all the CRUD operations.

**Comment by fmarco** [comment]
@AGranero12 Hi,
you're right :), i added the enhancement label to this issue, i think this could be a useful update!

**Comment by fmarco** [comment]
@AGranero12 Just released :)

**Comment by agranero** [comment]
That's great!! good job! :D

**Comment by fmarco** [comment]
you're welcome!
