### ISSUE TITLE
Duplicate mail body in when overriding the default template

### ISSUE THREAD

**Issue by hemangsk** [fmarco/django-rest-invitations#5]
Hi, thanks for the awesome library.

I wanted to override the default ``email_invite_message.txt``. After adding a email_invite_message.html in ``templates/invitations/email/``, but the resulting email's body becomes a combination of both default email_invite_message.txt and my new email_invite_message.html.

For example:
```
Content-Type: multipart/alternative;
 boundary="===============2473820804319092375=="
MIME-Version: 1.0
Subject: [example.com] Invitation to join example.com
From: webmaster@localhost
To: hemang14422m3@gmail.com
Date: Thu, 31 Jan 2019 06:21:46 -0000
Message-ID: <154891570685.82163.17885069461192854151@Hemangs-MacBook.local>

--===============2473820804319092375==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello
--===============2473820804319092375==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello
--===============2473820804319092375==--

-------------------------------------------------------------------------------
```

I tried to investigate but I'm not able find the reason for this weird mail body. Can you please give me an idea how this might be happening? 

Thanks again!

**Comment by fmarco** [comment]
@hemangsk Hello,

thanks for using this library!

The flow you followed is correct, the result you obtain too. Infact, django-invitations is able to send:

1) a pure text email
2) an html email
3) a multipart/alternative email (txt + html) and this is your case 

See here https://github.com/bee-keeper/django-invitations/blob/master/invitations/adapters.py#L34 for the general behaviour.

Let me know if you'll be able to solve the problem and the wanted behaviour.

**Comment by hemangsk** [comment]
Okay great, I understand the flow now. Thanks a lot for your help  🎉
