### ISSUE TITLE
Missing source distribution on pypi

### ISSUE THREAD

**Issue by jayvdb** [fmarco/django-rest-invitations#7]
https://pypi.org/project/django-rest-invitations/#files and https://pypi.org/simple/django-rest-invitations/ only contain wheels, without source distributions.

I would like to package this for openSUSE, on top of https://build.opensuse.org/package/show/home:jayvdb:django/python-django-invitations, so an sdist would be helpful.

**Comment by jayvdb** [comment]
Also it would be a good idea to switch to using `-` instead of `_` in the pypi distribution names, to match the repo name, etc.

**Comment by fastik17** [comment]
@fmarco when you update last release to pip ???

**Comment by jayvdb** [comment]
https://pypi.org/project/django-rest-invitations/ is still 0.1.1 Released: Jul 27, 2018

**Comment by fmarco** [comment]
i'm preparing the next release, sorry for the late, i'll update you asap!

**Comment by fastik17** [comment]
@jayvdb I mean DRF 3.10 compatibility 😄 
@fmarco ty!

**Comment by fmarco** [comment]
@fastik17 @jayvdb updated and released!
