### ISSUE TITLE
Deprecated list_route and detail_route in DRF 3.10

### ISSUE THREAD

**Issue by naveenkumarsangi** [fmarco/django-rest-invitations#8]
https://www.django-rest-framework.org/community/3.8-announcement/#action-decorator-replaces-list_route-and-detail_route

**Comment by fmarco** [comment]
Fixed by #11

**Comment by vittorio** [comment]
@fmarco can you please update pypi package? I think it might be major bump because current version might be not backward compatible with DRF<3.10

**Comment by fmarco** [comment]
@vittorio sure, i'm already working on the next release
